---
# sudo ansible-playbook -i env/local setup.yml
- hosts: all
  connection: local
  gather_facts: true
  become: yes

  vars:
    pip_install_packages:
      - name: docker

  tasks:
    - name: add youtube viewer repo
      apt_repository:
        repo: ppa:nilarimogard/webupd8
    - name: add mpv repo
      apt_repository:
        repo: ppa:mc3man/mpv-tests
    - name: add calibre repo
      apt_repository:
        repo: ppa:jonathonf/calibre
    - name: install youtube viewer
      apt:
        name: youtube-viewer
        state: present
    - name: install vlc
      apt:
        name: vlc
        state: present
    - name: install mpv
      apt:
        name: mpv
        state: present
    - name: install calibre
      apt:
        name: calibre
        state: present
  
  roles:
    - geerlingguy.pip
#    - geerlingguy.docker
#    - geerlingguy.git  
